<?php 
return [
	['id'=>'1','name'=>'SuperAdmin','home'=>'/'],
	['id'=>'2','name'=>'Admin','home'=>'/'],
	['id'=>'3','name'=>'Staff','home'=>'/'],
	['id'=>'4','name'=>'Student','home'=>'/'],
	['id'=>'5','name'=>'Admission Manager','home'=>'/'],
	['id'=>'6','name'=>'Admission Staff','home'=>'/'],
	['id'=>'7','name'=>'Admission RC','home'=>'/'],
	['id'=>'8','name'=>'Marketing Manager','home'=>'/'],
	['id'=>'9','name'=>'Marketing Staff','home'=>'/'],
	['id'=>'10','name'=>'Marketing RC','home'=>'/'],
	['id'=>'11','name'=>'Academic Manager','home'=>'/'],
	['id'=>'12','name'=>'Academic Staff','home'=>'/'],
	['id'=>'13','name'=>'Academic RC','home'=>'/'],
	['id'=>'14','name'=>'Exam Manager','home'=>'/'],
	['id'=>'15','name'=>'Exam Staff','home'=>'/'],
	['id'=>'16','name'=>'Finance Manager','home'=>'/'],
	['id'=>'17','name'=>'Finance Staff','home'=>'/'],
	['id'=>'18','name'=>'Finance RC','home'=>'/'],
	['id'=>'19','name'=>'Cource Leader','home'=>'/'],
	['id'=>'20','name'=>'Tutor','home'=>'/'],
	['id'=>'21','name'=>'Registered Applicant','home'=>'/preadmission/log_reg'],
	['id'=>'22','name'=>'Marketing Btec','home'=>'/'],
	['id'=>'24','name'=>'ACCA Applicant','home'=>'/pro/applicant/*'],
	['id'=>'25','name'=>'ACCA Staff','home'=>'/'],
];