<?php 
return [
	['id'=>'AD','name'=>'Andorra'],
	['id'=>'AE','name'=>'United Arab Emirates'],
	['id'=>'AF','name'=>'Afghanistan'],
	['id'=>'AG','name'=>'Antigua and/or Barbuda'],
	['id'=>'AI','name'=>'Anguilla'],
	['id'=>'AL','name'=>'Albania'],
	['id'=>'AM','name'=>'Armenia'],
	['id'=>'AN','name'=>'Netherlands Antilles'],
	['id'=>'AO','name'=>'Angola'],
	['id'=>'AQ','name'=>'Antarctica'],
	['id'=>'AR','name'=>'Argentina'],
	['id'=>'AT','name'=>'Austria'],
	['id'=>'AU','name'=>'Australia'],
	['id'=>'AW','name'=>'Aruba'],
	['id'=>'AZ','name'=>'Azerbaijan'],
	['id'=>'BA','name'=>'Bosnia and Herzegovina'],
	['id'=>'BB','name'=>'Barbados'],
	['id'=>'BD','name'=>'Bangladesh'],
	['id'=>'BE','name'=>'Belgium'],
	['id'=>'BF','name'=>'Burkina Faso'],
	['id'=>'BG','name'=>'Bulgaria'],
	['id'=>'BH','name'=>'Bahrain'],
	['id'=>'BI','name'=>'Burundi'],
	['id'=>'BJ','name'=>'Benin'],
	['id'=>'BM','name'=>'Bermuda'],
	['id'=>'BN','name'=>'Brunei Darussalam'],
	['id'=>'BO','name'=>'Bolivia'],
	['id'=>'BR','name'=>'Brazil'],
	['id'=>'BS','name'=>'Bahamas'],
	['id'=>'BT','name'=>'Bhutan'],
	['id'=>'BV','name'=>'Bouvet Island'],
	['id'=>'BW','name'=>'Botswana'],
	['id'=>'BY','name'=>'Belarus'],
	['id'=>'BZ','name'=>'Belize'],
	['id'=>'CA','name'=>'Canada'],
	['id'=>'CC','name'=>'Cocos (Keeling) Islands'],
	['id'=>'CF','name'=>'Central African Republic'],
	['id'=>'CG','name'=>'Congo'],
	['id'=>'CH','name'=>'Switzerland'],
	['id'=>'CI','name'=>'Ivory Coast'],
	['id'=>'CK','name'=>'Cook Islands'],
	['id'=>'CL','name'=>'Chile'],
	['id'=>'CM','name'=>'Cameroon'],
	['id'=>'CN','name'=>'China'],
	['id'=>'CO','name'=>'Colombia'],
	['id'=>'CR','name'=>'Costa Rica'],
	['id'=>'CU','name'=>'Cuba'],
	['id'=>'CV','name'=>'Cape Verde'],
	['id'=>'CX','name'=>'Christmas Island'],
	['id'=>'CY','name'=>'Cyprus'],
	['id'=>'CZ','name'=>'Czech Republic'],
	['id'=>'DE','name'=>'Germany'],
	['id'=>'DJ','name'=>'Djibouti'],
	['id'=>'DK','name'=>'Denmark'],
	['id'=>'DM','name'=>'Dominica'],
	['id'=>'DO','name'=>'Dominican Republic'],
	['id'=>'DS','name'=>'American Samoa'],
	['id'=>'DZ','name'=>'Algeria'],
	['id'=>'EC','name'=>'Ecuador'],
	['id'=>'EE','name'=>'Estonia'],
	['id'=>'EG','name'=>'Egypt'],
	['id'=>'EH','name'=>'Western Sahara'],
	['id'=>'ER','name'=>'Eritrea'],
	['id'=>'ES','name'=>'Spain'],
	['id'=>'ET','name'=>'Ethiopia'],
	['id'=>'FI','name'=>'Finland'],
	['id'=>'FJ','name'=>'Fiji'],
	['id'=>'FK','name'=>'Falkland Islands (Malvinas)'],
	['id'=>'FM','name'=>'Micronesia, Federated States of'],
	['id'=>'FO','name'=>'Faroe Islands'],
	['id'=>'FR','name'=>'France'],
	['id'=>'FX','name'=>'France, Metropolitan'],
	['id'=>'GA','name'=>'Gabon'],
	['id'=>'GB','name'=>'United Kingdom'],
	['id'=>'GD','name'=>'Grenada'],
	['id'=>'GE','name'=>'Georgia'],
	['id'=>'GF','name'=>'French Guiana'],
	['id'=>'GH','name'=>'Ghana'],
	['id'=>'GI','name'=>'Gibraltar'],
	['id'=>'GL','name'=>'Greenland'],
	['id'=>'GM','name'=>'Gambia'],
	['id'=>'GN','name'=>'Guinea'],
	['id'=>'GP','name'=>'Guadeloupe'],
	['id'=>'GQ','name'=>'Equatorial Guinea'],
	['id'=>'GR','name'=>'Greece'],
	['id'=>'GS','name'=>'South Georgia South Sandwich Islands'],
	['id'=>'GT','name'=>'Guatemala'],
	['id'=>'GU','name'=>'Guam'],
	['id'=>'GW','name'=>'Guinea-Bissau'],
	['id'=>'GY','name'=>'Guyana'],
	['id'=>'HK','name'=>'Hong Kong'],
	['id'=>'HM','name'=>'Heard and Mc Donald Islands'],
	['id'=>'HN','name'=>'Honduras'],
	['id'=>'HR','name'=>'Croatia (Hrvatska)'],
	['id'=>'HT','name'=>'Haiti'],
	['id'=>'HU','name'=>'Hungary'],
	['id'=>'ID','name'=>'Indonesia'],
	['id'=>'IE','name'=>'Ireland'],
	['id'=>'IL','name'=>'Israel'],
	['id'=>'IN','name'=>'India'],
	['id'=>'IO','name'=>'British lndian Ocean Territory'],
	['id'=>'IQ','name'=>'Iraq'],
	['id'=>'IR','name'=>'Iran (Islamic Republic of)'],
	['id'=>'IS','name'=>'Iceland'],
	['id'=>'IT','name'=>'Italy'],
	['id'=>'JM','name'=>'Jamaica'],
	['id'=>'JO','name'=>'Jordan'],
	['id'=>'JP','name'=>'Japan'],
	['id'=>'KE','name'=>'Kenya'],
	['id'=>'KG','name'=>'Kyrgyzstan'],
	['id'=>'KH','name'=>'Cambodia'],
	['id'=>'KI','name'=>'Kiribati'],
	['id'=>'KM','name'=>'Comoros'],
	['id'=>'KN','name'=>'Saint Kitts and Nevis'],
	['id'=>'KP','name'=>'Korea, Democratic People\'\'s Republic of'],
	['id'=>'KR','name'=>'Korea, Republic of'],
	['id'=>'KW','name'=>'Kuwait'],
	['id'=>'KY','name'=>'Cayman Islands'],
	['id'=>'KZ','name'=>'Kazakhstan'],
	['id'=>'LA','name'=>'Lao People\'\'s Democratic Republic'],
	['id'=>'LB','name'=>'Lebanon'],
	['id'=>'LC','name'=>'Saint Lucia'],
	['id'=>'LI','name'=>'Liechtenstein'],
	['id'=>'LK','name'=>'Sri Lanka'],
	['id'=>'LR','name'=>'Liberia'],
	['id'=>'LS','name'=>'Lesotho'],
	['id'=>'LT','name'=>'Lithuania'],
	['id'=>'LU','name'=>'Luxembourg'],
	['id'=>'LV','name'=>'Latvia'],
	['id'=>'LY','name'=>'Libyan Arab Jamahiriya'],
	['id'=>'MA','name'=>'Morocco'],
	['id'=>'MC','name'=>'Monaco'],
	['id'=>'MD','name'=>'Moldova, Republic of'],
	['id'=>'ME','name'=>'Montenegro'],
	['id'=>'MG','name'=>'Madagascar'],
	['id'=>'MH','name'=>'Marshall Islands'],
	['id'=>'MK','name'=>'Macedonia'],
	['id'=>'ML','name'=>'Mali'],
	['id'=>'MM','name'=>'Myanmar'],
	['id'=>'MN','name'=>'Mongolia'],
	['id'=>'MO','name'=>'Macau'],
	['id'=>'MP','name'=>'Northern Mariana Islands'],
	['id'=>'MQ','name'=>'Martinique'],
	['id'=>'MR','name'=>'Mauritania'],
	['id'=>'MS','name'=>'Montserrat'],
	['id'=>'MT','name'=>'Malta'],
	['id'=>'MU','name'=>'Mauritius'],
	['id'=>'MV','name'=>'Maldives'],
	['id'=>'MW','name'=>'Malawi'],
	['id'=>'MX','name'=>'Mexico'],
	['id'=>'MY','name'=>'Malaysia'],
	['id'=>'MZ','name'=>'Mozambique'],
	['id'=>'NA','name'=>'Namibia'],
	['id'=>'NC','name'=>'New Caledonia'],
	['id'=>'NE','name'=>'Niger'],
	['id'=>'NF','name'=>'Norfork Island'],
	['id'=>'NG','name'=>'Nigeria'],
	['id'=>'NI','name'=>'Nicaragua'],
	['id'=>'NL','name'=>'Netherlands'],
	['id'=>'NO','name'=>'Norway'],
	['id'=>'NP','name'=>'Nepal'],
	['id'=>'NR','name'=>'Nauru'],
	['id'=>'NU','name'=>'Niue'],
	['id'=>'NZ','name'=>'New Zealand'],
	['id'=>'OM','name'=>'Oman'],
	['id'=>'PA','name'=>'Panama'],
	['id'=>'PE','name'=>'Peru'],
	['id'=>'PF','name'=>'French Polynesia'],
	['id'=>'PG','name'=>'Papua New Guinea'],
	['id'=>'PH','name'=>'Philippines'],
	['id'=>'PK','name'=>'Pakistan'],
	['id'=>'PL','name'=>'Poland'],
	['id'=>'PM','name'=>'St. Pierre and Miquelon'],
	['id'=>'PN','name'=>'Pitcairn'],
	['id'=>'PR','name'=>'Puerto Rico'],
	['id'=>'PT','name'=>'Portugal'],
	['id'=>'PW','name'=>'Palau'],
	['id'=>'PY','name'=>'Paraguay'],
	['id'=>'QA','name'=>'Qatar'],
	['id'=>'RE','name'=>'Reunion'],
	['id'=>'RO','name'=>'Romania'],
	['id'=>'RS','name'=>'Serbia'],
	['id'=>'RU','name'=>'Russian Federation'],
	['id'=>'RW','name'=>'Rwanda'],
	['id'=>'SA','name'=>'Saudi Arabia'],
	['id'=>'SB','name'=>'Solomon Islands'],
	['id'=>'SC','name'=>'Seychelles'],
	['id'=>'SD','name'=>'Sudan'],
	['id'=>'SE','name'=>'Sweden'],
	['id'=>'SG','name'=>'Singapore'],
	['id'=>'SH','name'=>'St. Helena'],
	['id'=>'SI','name'=>'Slovenia'],
	['id'=>'SJ','name'=>'Svalbarn and Jan Mayen Islands'],
	['id'=>'SK','name'=>'Slovakia'],
	['id'=>'SL','name'=>'Sierra Leone'],
	['id'=>'SM','name'=>'San Marino'],
	['id'=>'SN','name'=>'Senegal'],
	['id'=>'SO','name'=>'Somalia'],
	['id'=>'SR','name'=>'Suriname'],
	['id'=>'ST','name'=>'Sao Tome and Principe'],
	['id'=>'SV','name'=>'El Salvador'],
	['id'=>'SY','name'=>'Syrian Arab Republic'],
	['id'=>'SZ','name'=>'Swaziland'],
	['id'=>'TC','name'=>'Turks and Caicos Islands'],
	['id'=>'TD','name'=>'Chad'],
	['id'=>'TF','name'=>'French Southern Territories'],
	['id'=>'TG','name'=>'Togo'],
	['id'=>'TH','name'=>'Thailand'],
	['id'=>'TJ','name'=>'Tajikistan'],
	['id'=>'TK','name'=>'Tokelau'],
	['id'=>'TM','name'=>'Turkmenistan'],
	['id'=>'TN','name'=>'Tunisia'],
	['id'=>'TO','name'=>'Tonga'],
	['id'=>'TP','name'=>'East Timor'],
	['id'=>'TR','name'=>'Turkey'],
	['id'=>'TT','name'=>'Trinidad and Tobago'],
	['id'=>'TV','name'=>'Tuvalu'],
	['id'=>'TW','name'=>'Taiwan'],
	['id'=>'TY','name'=>'Mayotte'],
	['id'=>'TZ','name'=>'Tanzania, United Republic of'],
	['id'=>'UA','name'=>'Ukraine'],
	['id'=>'UG','name'=>'Uganda'],
	['id'=>'UM','name'=>'United States minor outlying islands'],
	['id'=>'US','name'=>'United States'],
	['id'=>'UY','name'=>'Uruguay'],
	['id'=>'UZ','name'=>'Uzbekistan'],
	['id'=>'VA','name'=>'Vatican City State'],
	['id'=>'VC','name'=>'Saint Vincent and the Grenadines'],
	['id'=>'VE','name'=>'Venezuela'],
	['id'=>'VG','name'=>'Virgin Islands (British)'],
	['id'=>'VI','name'=>'Virgin Islands (U.S.)'],
	['id'=>'VN','name'=>'Vietnam'],
	['id'=>'VU','name'=>'Vanuatu'],
	['id'=>'WF','name'=>'Wallis and Futuna Islands'],
	['id'=>'WS','name'=>'Samoa'],
	['id'=>'XK','name'=>'Kosovo'],
	['id'=>'YE','name'=>'Yemen'],
	['id'=>'YU','name'=>'Yugoslavia'],
	['id'=>'ZA','name'=>'South Africa'],
	['id'=>'ZM','name'=>'Zambia'],
	['id'=>'ZR','name'=>'Zaire'],
	['id'=>'ZW','name'=>'Zimbabwe'],
];